Add documentation on the StatusService
mono/md-website pull request #70
Opened 2017-09-28 17:25 UTC by iainx

If https://github.com/mono/monodevelop/pull/3100 is merged, here is some documentation for it

2017-09-28 19:18 UTC, akoeplinger requested changes

2017-09-28 19:18 UTC, akoeplinger commented on developers/articles/status-service.md
> +  - /StatusService/
those redirects are for keeping the links from the old MediaWiki website working, you don't really need to add them on a new page

2017-09-28 19:18 UTC, akoeplinger commented on developers/articles/status-service.md
> +    icon.Dispose ();
missing backticks at the end to close the code block

2018-03-08 22:11 UTC, akoeplinger commented
@iainx is this still in progress?

2018-03-12 10:41 UTC, iainx commented
The code never got merged, and has dropped off the radar. I'll close this and reopen if the code ever gets merged

2018-03-12 10:41 UTC, closed without merging